### ISSUE TITLE
Introductory screencast not loading

### ISSUE THREAD

**Issue by andyw8** [pry/pry.github.com#22]
Chrome reports:

> Mixed Content: The page at 'https://pryrepl.org/' was loaded over HTTPS, but requested an insecure resource 'http://player.vimeo.com/video/26391171?title=0&byline=0&portrait=0'. This request has been blocked; the content must be served over HTTPS.

**Comment by kyrylo** [comment]
Seems to be back now. Not sure what happened, though.

**Comment by andyw8** [comment]
For me, It's still broken for me in both Safari and Chrome.

(http://pryrepl.org/ works but https://pryrepl.org/ doesn't)

**Comment by andrehjr** [comment]
Fixed by #25 on pry.github.io
