### ISSUE TITLE
API Docs link is broken

### ISSUE THREAD

**Issue by AlexWayfer** [pry/pry.github.com#24]
Hello.

This link is broken:

![image](https://user-images.githubusercontent.com/6510020/81971012-177b3f00-9629-11ea-8b4e-30869429615e.png)

https://rdoc.info/github/pry/pry/master/Pry

![image](https://user-images.githubusercontent.com/6510020/81971039-22ce6a80-9629-11ea-8012-715329cb07b0.png)

**Comment by andrehjr** [comment]
That link is no longer broken.
